references:
  container_config_node12: &container_config_node12
      working_directory: ~/project/build
      docker:
        - image: circleci/node:12-browsers
  workspace_root: &workspace_root
    ~/project
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root
  npm_cache_keys: &npm_cache_keys
    keys:
        - v11-dependency-npm-{{ checksum "package.json" }}-
        - v11-dependency-npm-{{ checksum "package.json" }}
        - v11-dependency-npm-

  cache_npm_cache: &cache_npm_cache
    save_cache:
        key: v11-dependency-npm-{{ checksum "package.json" }}-{{ epoch }}
        paths:
        - ./node_modules/

  restore_npm_cache: &restore_npm_cache
    restore_cache:
        <<: *npm_cache_keys

  filters_only_master: &filters_only_master
    branches:
      only: master

  filters_ignore_master: &filters_ignore_master
    branches:
      ignore: master

  filters_ignore_tags: &filters_ignore_tags
    tags:
      ignore: /.*/

  filters_version_tag: &filters_version_tag
    tags:
      only:
        - /^v?\d+\.\d+\.\d+(?:-beta\.\d+)?$/
    branches:
      ignore: /.*/
version: 2
jobs:
  build:
    <<: *container_config_node12
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - store_artifacts:
          path: build-state
          destination: build-state
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - build
workflows:
  version: 2
  build:
    jobs:
      - build
